version: '3.0'

services:
  token: 
    container_name: vany-micro-phase
    image: vany-micro-phase
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8761:8761 
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
    networks:
      - servicenet 

networks: 
  servicenet: