version: '3.0'

services:
  token: 
    container_name: vany-token
    image: vany-token
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 7000:7000
      - 7001:7001
      - 7002:7002
    networks:
      - servicenet 

networks: 
  servicenet: